### PR TITLE
Reduce API calls by downloading avatars directly

### PR DESCRIPTION
**Pull request by ask0n**
did some cleanup:

- [x]  `_no_avatar.jpg` was renamed into `.no_avatar.jpg` to survive `rm` commands
- [x] download avatars action is triggered against generated json, to save time on actual data collection and reduce API calls. Avatars won't change quickly but users can leave location while script is running
- [x] image name stores user id, too keep fancy photos for users who changes nicknames and avatars often ;)
- [x] small restructure to not repeat `Start harvesting data:` in a loop and countdown timer to indicate actual pause
- [x] added `.gitignore`
- [x] linter
- [x] introduced `speed_kmh` parameter to calculate dynamic timeout between `GetLocatedRequest` operations. TG reduce to return modified data if distance between points is too high and time between requests is too low. It looks like save "travel speed" should be less than 100km/h
- [x] added exception for `FloodWaitError`

### CODE REVIEW

**Comment by IvanGlinkin** [comment]
hey man. let me check it tomorrow and if it's working well will pull you request

**Comment by IvanGlinkin** [comment]
just launch the script and see results on the map and compare the same with my out original output. Seems like the combine of coordinates isn't working or the points of collection don't collect it all. 
if you see the original output - you can see the proper square but right now it like chaotic 
Screenshot 2024-05-01 at 20 29 27

**Comment by IvanGlinkin** [comment]
yeah, the second one screenshot is what i meant - it's showing more accurate locations.
I liked what you did regarding frontend - great job) thanks for allocating your time and efforts. Really appreciate it
But due to the application is not working - there is no point of frontend. let's find out together what has been broken in logic, fix it and put all of your addons to the master branch :)

**Comment by IvanGlinkin** [comment]
any luck so far?

**Comment by ask0n** [comment]
> any luck so far?

hey, yes, lemme prepare a new PR. Collected data looks identical now but I discovered that `https://t.me` url also throttles requests and returns a dummy page. Need to update logic to not fetch default logo instead of avatar.

**Comment by ant-on-stellar** [comment]
@IvanGlinkin looks like I can't open a new PR:
image

**Pull request merged**
